### ISSUE TITLE
Feature Request: Case Insensitive "Contains" searching

### ISSUE THREAD

**Issue by JaronrH** [bradwestness/collate-dot-net#5]
As a feature request, I would like to see the ability to perform case insensitive searches done.  Thanks!

**Comment by bradwestness** [comment]
That depends on the underlying data source, i.e. if you're querying against a SQL Server database, string comparisons are case-insensitive by default, so filtering with Collate.NET will be case-insensitive. However if the underlying dataSource is in-memory or a case-sensitive database, it won't be. I think in those cases your best bet would be to rewrite the filter value using .ToUpper() or similar.

I'm not sure there would be a non-kludgey way to implement this otherwise,
